Algoritmo "EsolhaVoto"

Var
   voto : caractere

Inicio
      Escreval("Digite seu voto: ")
      Leia (voto)
      
      Escolha voto
      caso "20"
           Escreval("Você votou no candidato José")
      caso "30"
           Escreval("Você votou na candidata Maria")
      caso "40"
           Escreval("Você votou na candidata Gisele")
      outrocaso
               Escreval("Voto nulo")
      fimEscolha

Fimalgoritmo